Repository Mantecado-hub/mantecado-hub-2, pull requests merged in 2024-12, with the labels that each got.

#51 Añadidos test en Feature/search querys
  app/modules/explore/tests/__init__.py
  app/modules/explore/tests/test_unit.py
Labels: enhancement, priority: medium, QA, difficulty: medium

#77 Nuevo workflow que comprueba los mensajes de PR
  .github/workflows/pr-message-check.yml
Labels: enhancement, priority: low, difficulty: medium, developer

#86 Feat: añadido workflow para las dependencias
  .github/workflows/checkDependences.yml
Labels: enhancement, priority: low, difficulty: low

#99 Fix: arreglar warnings en los test
  app/modules/auth/models.py
  app/modules/community/models.py
  migrations/versions/7180f6c7dffa_migrations.py
Labels: bug, priority: medium, QA, difficulty: medium

#101 Feat: añadido workflow para las releases
  .github/workflows/release-on-version.yml
Labels: enhancement, priority: low, difficulty: low, developer

#111 Test: realizado test de selenium explore
  .env.local.example
  .env.vagrant.example
  app/modules/explore/repositories.py
  app/modules/explore/tests/test_integration.py
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_unit.py
Labels: enhancement, priority: medium, difficulty: hard, developer

#113 Feat: Mejora de Fakenodo
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
Labels: enhancement, priority: medium, difficulty: low, developer

#115 Test: Nuevos test unitarios Fakenodo
  app/modules/fakenodo/tests/test_unit.py
Labels: enhancement, difficulty: low, developer

#116 Feat: Mejora del front searchQuery
  app/modules/explore/templates/explore/index.html
Labels: enhancement, priority: low, difficulty: low, developer

#124 Style: Cambio en el boton Search User
  app/templates/base_template.html
Labels: priority: medium, difficulty: low, developer
